### ISSUE TITLE
ValueError: {dt} not found

### ISSUE THREAD

**Issue by zillionare** [zillionare/backtesting#11]
if one day's position contains the following two entries:

```
(dt, None, 0, 0, 0),
(dt, "xxxxxx.XSHG", 100, 100, 0)
```

then position extending action will be skipped. And if there's no operation on date `dt + 1`, `dt + 2`, then these days will have no position entry(an empty entry is needed), thus the following exception may raises:

```
2022-06-23 02:31:06,940 E 16 backtest.common.helper:decorated_function:89 | 2020-03-18 not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/backtest/common/helper.py", line 81, in decorated_function
    result = await f(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/backtest/web/interfaces.py", line 241, in sell_percent
    result = await request.ctx.broker.sell(security, price, volume, order_time)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1055, in sell
    return await self._sell(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1136, in _sell
    return await self._fill_sell_order(en, mean_price, filled)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1035, in _fill_sell_order
    await self._update_assets(refund, en.bid_time)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 938, in _update_assets
    await self.recalc_assets(end)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 265, in recalc_assets
    position = self.get_position(end, position_dtype)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 228, in get_position
    raise ValueError(f"{dt} not found")
ValueError: 2020-03-18 not found
```
when re-calcing assets

**Comment by zillionare** [comment]
fixed in 8990a43e9c837dc07301033e6ac914e8ae8d08c9
