### ISSUE TITLE
failed: 499, -8 获取600361.XSHG在2022-08-11的行情数据失败

### ISSUE THREAD

**Issue by Johnny-168** [zillionare/backtesting#20]
# Describe the bug
600361.XSHG在2022-08-11是正常上市交易。获取此股票行情数据失败。

# To Reproduce
按比例卖出股票 failed: 499, -8 获取600361.XSHG在2022-08-11的行情数据失败，请检查日期是否为交易日，或者当天是否停牌
Traceback (most recent call last):
  File "C:/Users/wx/PycharmProjects/stock_program/zillionare/回测_交易_20220801/交易_收盘前/3_回测并整理交易数据_盘前.py", line 160, in <module>
    sell_info = sell(date, df_sell, path_, order_df) if not df_sell_n.empty else print('没有股票需要卖出')
  File "C:\Users\wx\PycharmProjects\stock_program\zillionare\回测_交易_20220801\交易_收盘前\config_收盘前回测.py", line 123, in sell
    sell_info = client.sell_percent(**sell_dic)
  File "C:\Users\wx\anaconda3\envs\stock_quant\lib\site-packages\traderclient\client.py", line 543, in sell_percent
    r = post_json(url, params=parameters, headers=self.headers)
  File "C:\Users\wx\anaconda3\envs\stock_quant\lib\site-packages\traderclient\transport.py", line 107, in post_json
    result = process_response_result(rsp, action)
  File "C:\Users\wx\anaconda3\envs\stock_quant\lib\site-packages\traderclient\transport.py", line 63, in process_response_result
    raise TradeError(rsp.status_code, rsp.text)
traderclient.errors.TradeError: -8 获取600361.XSHG在2022-08-11的行情数据失败，请检查日期是否为交易日，或者当天是否停牌: (499, '-8 获取600361.XSHG在2022-08-11的行情数据失败，请检查日期是否为交易日，或者当天是否停牌')

# Expected behavior
No expectation

# Version
backtest version: backtesting 0.4.8

**Comment by zillionare** [comment]
在0.4.9中无法重现。代码如下：
```
    code = "600361.XSHG"
    client.buy(code, 2000, 500, order_time=datetime.datetime(2021,7,23, 9, 31))
    client.sell(code, 0.1, 500, order_time=datetime.datetime(2021, 8, 11, 15))
```

后面再发现此问题，请先通过Stock.get_trade_price_limits, Stock.get_bars, Stock.batch_get_day_level_bars_in_range检查一下，数据是否在我们的数据库中存在。如果存在，则是backtesting的问题。否则，可能是omega的临时性问题。
