### ISSUE TITLE
300692.XSHE ，在2021-04-13 卖出失败。

### ISSUE THREAD

**Issue by Johnny-168** [zillionare/backtesting#26]
# Describe the bug
account: johnny_event_bk3_v18-dac6
300692.XSHE ，在2021-04-13 卖出失败。

2021-04-13 00:00:00 持仓：
 [('000728.XSHE', 17500., 17500.,  9.03      )
 ('002297.XSHE', 20800., 20800.,  7.6       )
 ('603377.XSHG',  8100.,  8100., 20.        )
 ('300692.XSHE', 10400., 10400., 15.47      )
 ('600317.XSHG', 43600., 43600.,  2.61999982)
 ('300011.XSHE', 16600., 16600.,  6.88      )
 ('002165.XSHE', 19400., 19400.,  5.87      )]

按比例卖出股票 failed: 499, invalid type promotion with structured datatype(s).
Traceback (most recent call last):
  File "C:/Users/wx/PycharmProjects/stock_program/zillionare/回测_20210104/3_回测并整理交易数据.py", line 164, in <module>
    sell_info = sell(date, df_sell, path_, order_df) if not df_sell_n.empty else print('没有股票需要卖出')
  File "C:\Users\wx\PycharmProjects\stock_program\zillionare\回测_20210104\config_回测交易2.py", line 124, in sell
    sell_info = client.sell_percent(**sell_dic)
  File "C:\Users\wx\anaconda3\envs\stock_quant\lib\site-packages\traderclient\client.py", line 543, in sell_percent
    r = post_json(url, params=parameters, headers=self.headers)
  File "C:\Users\wx\anaconda3\envs\stock_quant\lib\site-packages\traderclient\transport.py", line 107, in post_json
    result = process_response_result(rsp, action)
  File "C:\Users\wx\anaconda3\envs\stock_quant\lib\site-packages\traderclient\transport.py", line 63, in process_response_result
    raise TradeError(rsp.status_code, rsp.text)
traderclient.errors.TradeError: invalid type promotion with structured datatype(s).: (499, 'invalid type promotion with structured datatype(s).')

# Version
backtest version:  0.4.9

**Comment by zillionare** [comment]
无法重现：
```
    for code in ("000728.XSHE", "002297.XSHE", "603377.XSHG", "300692.XSHE", "300011.XSHE", "002165.XSHE"):
        client.buy(code, 2000, 500, order_time=datetime.datetime(2021, 3, 29, 9, 31))
    

    client.sell("300692.XSHE", 0.1, 500, order_time=datetime.datetime(2021, 4, 13, 15))
```
