### ISSUE TITLE
'002422.XSHE'，卖出报错。开始时间：20220829； 结束时间20220901

### ISSUE THREAD

**Issue by Johnny-168** [zillionare/backtesting#27]
# Describe the bug
9月1日早盘获取开盘价后进行回测运算。'002422.XSHE', 卖出报错。

2022-09-01 00:00:00 持仓：
 [('603955.XSHG',  6400.,  6400., 18.28000122)
 ('002422.XSHE',  5200.,  5200., 22.4       )
 ('002615.XSHE', 14400., 14400.,  8.12      )
 ('600775.XSHG', 11900., 11900.,  9.81000066)]

按比例卖出股票 failed: 499, Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/backtest/common/helper.py", line 83, in decorated_function
    result = await f(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/backtest/web/interfaces.py", line 239, in sell_percent
    result = await request.ctx.broker.sell(security, price, sellable, order_time)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1087, in sell
    return await self._sell(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1096, in _sell
    await self._before_trade(bid_time)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 803, in _before_trade
    await self._fillup_positions(bid_time)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 837, in _fillup_positions
    dr_info = await feed.get_dr_factor(secs, frames)
  File "/usr/local/lib/python3.8/dist-packages/backtest/feed/zillionarefeed.py", line 114, in get_dr_factor
    async for sec, bars in Stock.batch_get_day_level_bars_in_range(
  File "/usr/local/lib/python3.8/dist-packages/omicron/models/stock.py", line 291, in batch_get_day_level_bars_in_range
    cached = await cls._batch_get_cached_bars_n(frame_type, 1, end, codes)
  File "/usr/local/lib/python3.8/dist-packages/omicron/models/stock.py", line 822, in _batch_get_cached_bars_n
    barss = numpy_append_fields(barss, "code", codes, [("code", "O")])
  File "/usr/local/lib/python3.8/dist-packages/omicron/extensions/np.py", line 299, in numpy_append_fields
    result[names[i]] = data[i]
ValueError: could not broadcast input array from shape (4,) into shape (0,)

**Comment by zillionare** [comment]
错误因omicron导致。升级后解决了这个问题。
