### ISSUE TITLE
调用 metrics 报错。回测区间：8月29日至9月7日 

### ISSUE THREAD

**Issue by Johnny-168** [zillionare/backtesting#28]
# 9月7日收盘后回测。回测区间：8月29日至9月7日。
ValueError: could not broadcast input array from shape (4,) into shape (3,)

账户评估指标 failed: 499, Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/backtest/common/helper.py", line 83, in decorated_function
    result = await f(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/backtest/web/interfaces.py", line 353, in metrics
    metrics = await request.ctx.broker.metrics(start, end, baseline)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1332, in metrics
    await self.recalc_assets()
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 283, in recalc_assets
    closes = await feed.batch_get_close_price_in_range(secs, frames)
  File "/usr/local/lib/python3.8/dist-packages/backtest/feed/zillionarefeed.py", line 63, in batch_get_close_price_in_range
    async for sec, values in Stock.batch_get_day_level_bars_in_range(
  File "/usr/local/lib/python3.8/dist-packages/omicron/models/stock.py", line 291, in batch_get_day_level_bars_in_range
    cached = await cls._batch_get_cached_bars_n(frame_type, 1, end, codes)
  File "/usr/local/lib/python3.8/dist-packages/omicron/models/stock.py", line 823, in _batch_get_cached_bars_n
    barss = numpy_append_fields(barss, "code", codes, [("code", "O")])
  File "/usr/local/lib/python3.8/dist-packages/omicron/extensions/np.py", line 299, in numpy_append_fields
    result[names[i]] = data[i]
ValueError: could not broadcast input array from shape (4,) into shape (3,)

Traceback (most recent call last):
  File "C:/Users/wx/PycharmProjects/stock_program/zillionare/回测_交易_20220801/3_回测并整理交易数据_08.py", line 253, in <module>
    metrics = client.metrics()
  File "C:\Users\wx\anaconda3\envs\stock_quant\lib\site-packages\traderclient\client.py", line 616, in metrics
    return get(url, headers=self.headers, params=params)
  File "C:\Users\wx\anaconda3\envs\stock_quant\lib\site-packages\traderclient\transport.py", line 85, in get
    result = process_response_result(rsp, action)
  File "C:\Users\wx\anaconda3\envs\stock_quant\lib\site-packages\traderclient\transport.py", line 63, in process_response_result
    raise TradeError(rsp.status_code, rsp.text)
traderclient.errors.TradeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/backtest/common/helper.py", line 83, in decorated_function
    result = await f(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/backtest/web/interfaces.py", line 353, in metrics
    metrics = await request.ctx.broker.metrics(start, end, baseline)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1332, in metrics
    await self.recalc_assets()
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 283, in recalc_assets
    closes = await feed.batch_get_close_price_in_range(secs, frames)
  File "/usr/local/lib/python3.8/dist-packages/backtest/feed/zillionarefeed.py", line 63, in batch_get_close_price_in_range
    async for sec, values in Stock.batch_get_day_level_bars_in_range(
  File "/usr/local/lib/python3.8/dist-packages/omicron/models/stock.py", line 291, in batch_get_day_level_bars_in_range
    cached = await cls._batch_get_cached_bars_n(frame_type, 1, end, codes)
  File "/usr/local/lib/python3.8/dist-packages/omicron/models/stock.py", line 823, in _batch_get_cached_bars_n
    barss = numpy_append_fields(barss, "code", codes, [("code", "O")])
  File "/usr/local/lib/python3.8/dist-packages/omicron/extensions/np.py", line 299, in numpy_append_fields
    result[names[i]] = data[i]
ValueError: could not broadcast input array from shape (4,) into shape (3,)
: (499, 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/dist-packages/backtest/common/helper.py", line 83, in decorated_function\n    result = await f(request, *args, **kwargs)\n  File "/usr/local/lib/python3.8/dist-packages/backtest/web/interfaces.py", line 353, in metrics\n    metrics = await request.ctx.broker.metrics(start, end, baseline)\n  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1332, in metrics\n    await self.recalc_assets()\n  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 283, in recalc_assets\n    closes = await feed.batch_get_close_price_in_range(secs, frames)\n  File "/usr/local/lib/python3.8/dist-packages/backtest/feed/zillionarefeed.py", line 63, in batch_get_close_price_in_range\n    async for sec, values in Stock.batch_get_day_level_bars_in_range(\n  File "/usr/local/lib/python3.8/dist-packages/omicron/models/stock.py", line 291, in batch_get_day_level_bars_in_range\n    cached = await cls._batch_get_cached_bars_n(frame_type, 1, end, codes)\n  File "/usr/local/lib/python3.8/dist-packages/omicron/models/stock.py", line 823, in _batch_get_cached_bars_n\n    barss = numpy_append_fields(barss, "code", codes, [("code", "O")])\n  File "/usr/local/lib/python3.8/dist-packages/omicron/extensions/np.py", line 299, in numpy_append_fields\n    result[names[i]] = data[i]\nValueError: could not broadcast input array from shape (4,) into shape (3,)\n')

**Comment by Johnny-168** [comment]
账户持仓，002404 处于停牌状态。

模拟第8天: 2022-09-07 00:00:00 ==================================================
pos [('603955.XSHG',  6400.,  6400., 18.28000122)
 ('002615.XSHE', 14600., 14600.,  8.12      )
 ('600775.XSHG', 12100., 12100.,  9.81000065)
 ('002404.XSHE', 84000.,     0.,  7.14      )]
