### ISSUE TITLE
回测中，2022-10-21 卖出 300539.XSHE 失败

### ISSUE THREAD

**Issue by Johnny-168** [zillionare/backtesting#33]
# Describe the bug
回测中，2022-10-21 卖出 300539.XSHE 失败

df_sell_n:
            交易日期  股票名称  sell_time  sell_price event_bk3+ _merge
股票代码                                                              
sz300539 2022-10-21  横河精密 2022-10-21        8.98         -1   both

报错如下：
按比例卖出股票 failed: 499, -6 300539.XSHE现价未达到委托价:8.97
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/backtest/common/helper.py", line 83, in decorated_function
    result = await f(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/backtest/web/interfaces.py", line 239, in sell_percent
    result = await request.ctx.broker.sell(security, price, sellable, order_time)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1088, in sell
    return await self._sell(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1123, in _sell
    bars = self._remove_for_sell(
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1245, in _remove_for_sell
    raise EntrustError(
backtest.common.errors.EntrustError: 300539.XSHE现价未达到委托价:8.97: (-6,)

traderclient.errors.TradeError: -6 300539.XSHE现价未达到委托价:8.97
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/backtest/common/helper.py", line 83, in decorated_function
    result = await f(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/backtest/web/interfaces.py", line 239, in sell_percent
    result = await request.ctx.broker.sell(security, price, sellable, order_time)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1088, in sell
    return await self._sell(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1123, in _sell
    bars = self._remove_for_sell(
  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1245, in _remove_for_sell
    raise EntrustError(
backtest.common.errors.EntrustError: 300539.XSHE现价未达到委托价:8.97: (-6,)
: (499, '-6 300539.XSHE现价未达到委托价:8.97\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.8/dist-packages/backtest/common/helper.py", line 83, in decorated_function\n    result = await f(request, *args, **kwargs)\n  File "/usr/local/lib/python3.8/dist-packages/backtest/web/interfaces.py", line 239, in sell_percent\n    result = await request.ctx.broker.sell(security, price, sellable, order_time)\n  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1088, in sell\n    return await self._sell(*args, **kwargs)\n  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1123, in _sell\n    bars = self._remove_for_sell(\n  File "/usr/local/lib/python3.8/dist-packages/backtest/trade/broker.py", line 1245, in _remove_for_sell\n    raise EntrustError(\nbacktest.common.errors.EntrustError: 300539.XSHE现价未达到委托价:8.97: (-6,)\n')

# To Reproduce

# Expected behavior

# Screenshots

# Version
backtest version:   zillionare-trader-client   0.3.11

**Comment by zillionare** [comment]
因为日线最高价与分钟线最高价不一致导致。通过查看行情软件，他们也有同样问题。bt在这种情况下，会返回NO_ENOUGH_VOLUME错误，策略需要检测错误，重新挂单。
